# 파이썬 프로그래밍 테스트

### 답안은 pdf 또는 html로 저장하여 메일로 제출하시오 
- hjkim3@gmail.com
- Control-P 로 출력하면서 pdf로 저장하거나,
- File - Download as - HTML로 저장하면 됩니다

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## 아래 주어진 데이터프레임 df에 대해서 문제를 풀이하시오

In [12]:
d = {'city': ['서울', '부산', '대구', '대전', '광주'],
        'population': [990, 350, 250, 154, 150],
        'temp': [13, 16, 14, 13, 15]}

df = pd.DataFrame(d)
df

city  population  temp
0   서울         990    13
1   부산         350    16
2   대구         250    14
3   대전         154    13
4   광주         150    15

### (1) 인구(population)가 200 이상인 샘플(행)만 추출하시오

In [18]:
df[df['population'] >= 200]

city  population  temp
0   서울         990    13
1   부산         350    16
2   대구         250    14

### (2) 인구가 많은 순으로 (내림차순으로) 정렬한 데이터프레임을 만드시오

In [20]:
df.sort_values(by='population', ascending=False)

city  population  temp
0   서울         990    13
1   부산         350    16
2   대구         250    14
3   대전         154    13
4   광주         150    15

### (3) df의 5개 도시의 인구의 평균치를 구하고 인구가 이 평균치보다 적은 도시 행을 출력하시오

In [29]:
df[df['population']<df['population'].mean()]

city  population  temp
1   부산         350    16
2   대구         250    14
3   대전         154    13
4   광주         150    15

### (4) df2를 df2.csv 파일로 저장하는 프로그램을 작성하시오

In [34]:
df.to_csv('df2.csv')

## 아래의 (6,5) 모양의 어레이 x에 대해서 문제를 풀이하시오

In [33]:
x = np.arange(30).reshape(6,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

### (5) 위의 x에는 6개의 행이 있는데 홀수번째의 행만 추출한(즉, 샘플 데이터를 반으로 줄인) x2를 얻는 코드를 작성하시오

In [36]:
x[[0,2,4]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24]])

### (6) 위의 (6,5) 모양의 어레이 x에 대해서 각 행(row)의 합계를 우측에 기록한 후, 각 열(column)의 평균값을 아래에 나타내는 (7,6) 크기의 데이터프레임 df3을 만드시오


In [68]:
df = pd.DataFrame(x)
df['sum'] = df.sum(axis=1)
df.loc['6'] = df.mean()
df



0     1     2     3     4    sum
0   0.0   1.0   2.0   3.0   4.0   10.0
1   5.0   6.0   7.0   8.0   9.0   35.0
2  10.0  11.0  12.0  13.0  14.0   60.0
3  15.0  16.0  17.0  18.0  19.0   85.0
4  20.0  21.0  22.0  23.0  24.0  110.0
5  25.0  26.0  27.0  28.0  29.0  135.0
6  12.5  13.5  14.5  15.5  16.5   72.5

### (7) 위의 데이터프레임 df3의 수치 값만 포함하는 (7,6) 크기의 어레이 x3를 만드시오

In [71]:
x3 = df.values
x3

array([[  0. ,   1. ,   2. ,   3. ,   4. ,  10. ],
       [  5. ,   6. ,   7. ,   8. ,   9. ,  35. ],
       [ 10. ,  11. ,  12. ,  13. ,  14. ,  60. ],
       [ 15. ,  16. ,  17. ,  18. ,  19. ,  85. ],
       [ 20. ,  21. ,  22. ,  23. ,  24. , 110. ],
       [ 25. ,  26. ,  27. ,  28. ,  29. , 135. ],
       [ 12.5,  13.5,  14.5,  15.5,  16.5,  72.5]])

In [78]:
x2 = x3.sum(1).reshape(-1,1)
x2
x4 = np.hstack((x3, x2))
x5 = x4.mean(0)
np.vstack((x4, x5))

array([[  0. ,   1. ,   2. ,   3. ,   4. ,  10. ,  20. ],
       [  5. ,   6. ,   7. ,   8. ,   9. ,  35. ,  70. ],
       [ 10. ,  11. ,  12. ,  13. ,  14. ,  60. , 120. ],
       [ 15. ,  16. ,  17. ,  18. ,  19. ,  85. , 170. ],
       [ 20. ,  21. ,  22. ,  23. ,  24. , 110. , 220. ],
       [ 25. ,  26. ,  27. ,  28. ,  29. , 135. , 270. ],
       [ 12.5,  13.5,  14.5,  15.5,  16.5,  72.5, 145. ],
       [ 12.5,  13.5,  14.5,  15.5,  16.5,  72.5, 145. ]])

### (8) $x, y$ 의 입출력 관계가 $ y = 0.2x^2 -0.5x +2$와 같을 때 $ 0 < x < 5 $ 범위에서 $x, y$의 관계를 그래프로 그리시오